// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGESzoZN3gTO5LAamjW4UWnGpXwN5X5R4',
    appId: '1:570350156640:web:b8ae3570eda89181debc05',
    messagingSenderId: '570350156640',
    projectId: 'my-learninng-project2024',
    authDomain: 'my-learninng-project2024.firebaseapp.com',
    storageBucket: 'my-learninng-project2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9X5VH8JZJARW1io6qbeEXH86KzXeonME',
    appId: '1:570350156640:android:5bd4ad654a32d6c5debc05',
    messagingSenderId: '570350156640',
    projectId: 'my-learninng-project2024',
    storageBucket: 'my-learninng-project2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj8Fj8KNA5Gf1ae_Awz6nZkS0n1T99yjI',
    appId: '1:570350156640:ios:a199e54708fa67badebc05',
    messagingSenderId: '570350156640',
    projectId: 'my-learninng-project2024',
    storageBucket: 'my-learninng-project2024.appspot.com',
    iosBundleId: 'com.AndrewDmitrievsky.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj8Fj8KNA5Gf1ae_Awz6nZkS0n1T99yjI',
    appId: '1:570350156640:ios:5fe1d0b0a2757096debc05',
    messagingSenderId: '570350156640',
    projectId: 'my-learninng-project2024',
    storageBucket: 'my-learninng-project2024.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGESzoZN3gTO5LAamjW4UWnGpXwN5X5R4',
    appId: '1:570350156640:web:5f03291e25b0bd9bdebc05',
    messagingSenderId: '570350156640',
    projectId: 'my-learninng-project2024',
    authDomain: 'my-learninng-project2024.firebaseapp.com',
    storageBucket: 'my-learninng-project2024.appspot.com',
  );

}